---
- hosts: all
  pre_tasks:
      - name: Install libselinux-python
        sudo: true
        yum: name=libselinux-python state=present
  roles:
      - { role: goozbach.EPEL, sudo: yes }
      - { role: base, sudo: yes }
      - robbinsd
      - { role: nginx, sudo: yes }
  tasks:
      - debug: msg="Hello World"
