---
- hosts: all
  pre_tasks:
      - name: Install libselinux-python
        sudo: true
        yum: name=libselinux-python state=present
      - name: Ensure kaneara knows where itself is (IPv4)
        sudo: true
        lineinfile: dest=/etc/hosts line="127.0.0.1   kaneara"
      - name: Ensure kaneara knows where itself is (IPv6)
        sudo: true
        lineinfile: dest=/etc/hosts line="::1         kaneara"
  roles:
      - { role: goozbach.EPEL, sudo: yes }
      - { role: base, sudo: yes }
      - robbinsd
      - { role: nginx, sudo: yes }
      - { role: robbinsd.net, sudo: yes }
      - { role: tissuehub.org, sudo: yes }
      - { role: tissuehub, tissuehub_user: robbinsd, tissuehub_version: "1.1.1" }