---
- set_fact:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

- name: ensure forever is installed
  sudo: true
  npm: name=forever global=yes state=present

- name: checkout tissuehub repository
  remote_user: "{{tissuehub_user}}"
  git: repo={{repo}} dest={{app_dir}} accept_hostkey=yes

- name: ensure MongoDB is running
  sudo: true
  service: name=mongod state=started

- name: build app
  remote_user: "{{tissuehub_user}}"
  shell: chdir={{app_dir}} /usr/local/bin/meteor build --directory .builds/build-{{timestamp}}

- name: install npm dependencies
  remote_user: "{{tissuehub_user}}"
  shell: chdir={{app_dir}}/.builds/build-{{timestamp}}/bundle/programs/server npm install

- name: stop current running app
  remote_user: "{{tissuehub_user}}"
  shell: forever stopall
  ignore_errors: yes

- name: start tissuehub
  remote_user: "{{tissuehub_user}}"
  shell:  >
    PORT={{ port }}
    MONGO_URL={{ mongo_url }}
    ROOT_URL={{ "https://tissuehub.org/" }}
    forever start "{{app_dir}}"/.builds/build-{{timestamp}}/bundle/main.js
  async: 10
  poll: 1
