---
- name: ensure forever is installed
  sudo: true
  npm: name=forever global=yes state=present

- name: checkout tissuehub repository
  remote_user: "{{tissuehub_user}}"
  git: repo={{repo}} dest={{app_dir}} accept_hostkey=yes

- name: ensure MongoDB is running
  sudo: true
  service: name=mongod state=started

- name: stop current running app
  remote_user: "{{tissuehub_user}}"
  shell: forever stopall
  ignore_errors: yes

- name: remove current running app
  remote_user: "{{tissuehub_user}}"
  shell: chdir={{app_dir}} rm -rf bundle

- name: bundle app
  remote_user: "{{tissuehub_user}}"
  shell: chdir={{app_dir}} /usr/local/bin/meteor bundle bundle.tgz

- name: unbundle app
  remote_user: "{{tissuehub_user}}"
  shell: chdir={{app_dir}} tar -xzvf bundle.tgz

- name: install npm dependencies
  remote_user: "{{tissuehub_user}}"
  shell: chdir={{app_dir}}/bundle/programs/server npm install

- name: start tissuehub
  remote_user: "{{tissuehub_user}}"
  shell:  >
    PORT={{ port }}
    MONGO_URL={{ mongo_url }}
    ROOT_URL={{ "https://tissuehub.org/" }}
    forever start "{{ app_dir }}"/bundle/main.js
  async: 10
  poll: 1
