---
- name: install common packages
  yum: name={{ item }} state=present
  with_items:
   - vim-common
   - vim-minimal
   - vim-enhanced
   - git
   - make

- name: remove old version of npm
  yum: name=npm enablerepo=epel state=absent

- name: remove old verison of nodejs
  yum: name=nodejs-0.10.33 enablerepo=epel state=absent

- name: add nodesource repository
  shell: curl -sL https://rpm.nodesource.com/setup | bash -

- name: install nodejs 0.10.38
  yum: name=nodejs-0.10.38 state=present